BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogs.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=False)),
    path('accounts/', include('django.contrib.auth.urls')),
]

blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
    path('<int:pk>/create', views.CommentCreate.as_view(), name='comment-create'),
    path('create/', views.BlogCreate.as_view(), name='blog-create'),


]

blogs/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import User, PermissionsMixin, AbstractUser
from django.db import models
from django.urls import reverse


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """

        user = self.model(
            email=email,
            username=username,

        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email,
            username=username,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractUser):
    is_blogger = models.BooleanField(default=False)
    objects = MyUserManager()

    def has_perm(self, perm, obj=None):
        if perm == 'blogs.is_blogger':
            return self.is_blogger
        return True


class Blogger(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField(max_length=1000)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=200)
    blogger = models.ForeignKey('Blogger', on_delete=models.SET_NULL, null=True)
    post_date = models.DateField(null=True, blank=True)
    description = models.TextField(max_length=1000)

    class Meta:
        ordering = ['-post_date']

    def get_absolute_url(self):
        """Returns the url to access a particular blogger instance."""
        return reverse('blog-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


class Comment(models.Model):
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here")
    post_date = models.DateField(null=True, blank=True)
    blog = models.ForeignKey('Blog', on_delete=models.RESTRICT, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['post_date']

    def __str__(self):
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

blogs/views.py
import datetime
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.generic import CreateView

from blogs.models import Blog, Blogger, Comment


def index(request):
    """View function for home page of site."""

    num_blogs = Blog.objects.all().count()
    num_bloggers = Blogger.objects.count()

    context = {
        'num_blogs': num_blogs,
        'num_bloggers': num_bloggers,

    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'blogs/index.html', context=context)


class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 1

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class BloggerListView(generic.ListView):
    model = Blogger


class BlogDetailView(generic.DetailView):
    model = Blog


class BloggerDetailView(generic.DetailView):
    model = Blogger


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['description', ]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(CommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        # Add logged-in user as author of comment
        form.instance.user = self.request.user
        form.instance.post_date = datetime.date.today()
        # Associate comment with blog based on passed id
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(CommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-detail', kwargs={'pk': self.kwargs['pk'], })


class BlogCreate(PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ['title', 'description', ]
    permission_required = 'blogs.is_blogger'

    def form_valid(self, form):
        form.instance.blogger = self.request.user.blogger
        form.instance.post_date = datetime.date.today()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs', )

blogs/templates/blogs/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Blogs</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'blogs' %}">All blogs</a></li>
          <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
        </ul>
        {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
   {% endif %}
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}
          {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}
</div>
    </div>
  </div>
</body>
</html>

blogs/templates/blogs/blog_detail.html
{% extends "blogs/base_generic.html" %}

{% block content %}
  <h1>{{ blog.title }}</h1>
<p><strong>Post date:</strong> {{ blog.post_date }}</p>
  <p><strong>Author:</strong> <a href="{{ blog.blogger.get_absolute_url }}">{{ blog.blogger }}</a></p> <!-- author detail link not yet defined -->
  <strong>Description:</strong>
<hr>
  <p> {{ blog.description }}</p>


  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

    {% for comment in blog.comment_set.all %}
      <hr>
      <p>
        {{ comment.user}}({{ comment.post_date }})-{{ comment.description }}
      </p>
    {% endfor %}
  </div>
  {% if user.is_authenticated %}
     <a href="{% url 'comment-create' blog.id %}?next={{ request.path }}">Add a new comment</a>
   {% else %}
     <a href="{% url 'login' %}?next={{ request.path }}">Login</a> to add a new comment
   {% endif %}
{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends "blogs/base_generic.html" %}

{% block content %}
<p>Create Your Blog</p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blogs/templates/blogs/blog_list.html
{% extends "blogs/base_generic.html" %}

{% block content %}
  <h1>Blog List</h1>
  {% if blog_list %}
  <ul>
    {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> {{blog.post_date}}---<a href="{{ blog.blogger.get_absolute_url }}">{{blog.blogger}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

blogs/templates/blogs/blogger_detail.html
{% extends "blogs/base_generic.html" %}

{% block content %}
  <h1>Blogger: {{ blogger.last_name }}</h1>
<h3>Bio</h3>
  <p>{{ blogger.bio }}</p> <!-- blogger detail link not yet defined -->

  <div style="margin-left:20px;margin-top:20px">
    <h4>Blogs list</h4>

    {% for blog in blogger.blog_set.all %}
      <hr>
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> {{blog.post_date}}
      </li>
    {% endfor %}
  </div>
{% endblock %}

blogs/templates/blogs/blogger_list.html
{% extends "blogs/base_generic.html" %}

{% block content %}
  <h1>Blogger List</h1>
  {% if blogger_list %}
  <ul>
    {% for blogger in blogger_list %}
      <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger.name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Bloggers</p>
  {% endif %}

{% endblock %}

blogs/templates/blogs/comment_form.html
{% extends "blogs/base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blogs/templates/blogs/index.html
{% extends "blogs/base_generic.html" %}

{% block content %}
  <h1>Local Blog</h1>
  <p>Welcome to Blog site</p>
  <h2>Dynamic content</h2>
  <p>The blog has the following record counts:</p>
  <ul>
    <li><strong>Blogs:</strong> {{ num_blogs }}</li>
    <li><strong>Bloggers:</strong> {{ num_bloggers }}</li>
  </ul>
{% endblock %}